name: ML Continuous Integration

run-name: Run Python ML CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '!master'

jobs:
  ci:
    name: lint and test ml pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Python versions later than 3.9 are not supported by dslinter
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install requirements
        run: make requirements
      - name: Lint with mypy, flake8, pylint & dslinter
        run: make lint
      - name: Preprocess dataset
        run: make data
      - name: Train model
        run: make train
      - name: Test with pytest
        run: make test
      - name: Pytest coverage comment
        if: ${{ github.event_name == 'pull_request' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: false
          pytest-xml-coverage-path: src/tests/coverage/coverage.xml
          junitxml-path: src/tests/coverage/pytest.xml
      - name: create mllint report
        run: make report
      - name: comment mllint report
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filepath: reports/mllint.md