name: Python CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '!master'

jobs:
  ci:
    name: Run linter and tests
    uses: remla23-team5/cicd/.github/workflows/python-ci.yaml@main