name: Create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create release
    uses: remla23-team5/cicd/.github/workflows/release.yaml@update-release-snapshot
    secrets: inherit